#!/bin/bash

export IP_ADDR=$(hostname --ip)

# Substituting env variables in the config file and create a new file as a result
# The different file is created if we need to update env variables in the config after restart
# If not then the result of substitution might overwrite existing config file

APP_CONFIG_NAME=$(echo ${APP_CONFIG_TEMPLATE} | cut -d '.' -f 1)
APP_CONFIG="${APP_CONFIG_NAME}.properties"

if [ -n "${APP_CONFIG_TEMPLATE}" ]; then
  envsubst < ${APP_CONFIG_TEMPLATE} > $APP_CONFIG
  echo "New config is generated by substituting environment variables: $APP_CONFIG"
else
  >&2 echo "Environment variable APP_CONFIG_TEMPLATE is not specified"
  exit 1
fi

java -cp lib/ $(cat ${JAVA_OPTS} | xargs) -classpath conf:lib/* ${MAIN_CLASS} ${APP_CONFIG}
